export {
  MessageType,
  isExtensionMessage,
  isGetRepoStateResponse,
  isGetAuthStateResponse,
  isValidateGitHubTokenResponse,
  isDisconnectGitHubResponse,
  isGetRepositoryFactsResponse,
  isRepositoryFactsState,
  isSanitizedAuthState,
  type ExtensionMessage,
  type GetAuthStateMessage,
  type GetAuthStateResponse,
  type ValidateGitHubTokenMessage,
  type ValidateGitHubTokenResponse,
  type DisconnectGitHubMessage,
  type DisconnectGitHubResponse,
  type AuthStateUpdatedMessage,
  type GetRepositoryFactsMessage,
  type GetRepositoryFactsResponse,
  type RepositoryFactsUpdatedMessage,
} from "./messages";
export { useAuthState } from "./hooks/useAuthState";
